In [3]:
print("all ok")

all ok


In [4]:
from sklearn.preprocessing import OneHotEncoder
import numpy

In [5]:
document = ["my name is sunny and I love AI"]

In [6]:
documents = ["people watch movie", 
             "people watch cricket", 
             "people like movie", 
             "people like cricket"]

In [7]:
tokens = [sentence.lower().split() for sentence in document]

In [8]:
tokens

[['my', 'name', 'is', 'sunny', 'and', 'i', 'love', 'ai']]

In [9]:
all_words = [[word] for sentence in tokens for word in sentence]

In [10]:
all_words

[['my'], ['name'], ['is'], ['sunny'], ['and'], ['i'], ['love'], ['ai']]

##### sparse_output=False means the encoder returns a NumPy array instead of a sparse matrix. This makes the output easier

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

In [11]:
encoder = OneHotEncoder(sparse_output=False)

In [12]:
encoder.fit(all_words)

,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values within a single feature, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute... versionadded:: 0.20",'auto'
,"drop drop: {'first', 'if_binary'} or an array-like of shape (n_features,), default=NoneSpecifies a methodology to use to drop one of the categories perfeature. This is useful in situations where perfectly collinearfeatures cause problems, such as when feeding the resulting datainto an unregularized linear regression model.However, dropping one category breaks the symmetry of the originalrepresentation and can therefore induce a bias in downstream models,for instance for penalized linear classification or regression models.- None : retain all features (the default).- 'first' : drop the first category in each feature. If only one category is present, the feature will be dropped entirely.- 'if_binary' : drop the first category in each feature with two categories. Features with 1 or more than 2 categories are left intact.- array : ``drop[i]`` is the category in feature ``X[:, i]`` that should be dropped.When `max_categories` or `min_frequency` is configured to groupinfrequent categories, the dropping behavior is handled after thegrouping... versionadded:: 0.21 The parameter `drop` was added in 0.21... versionchanged:: 0.23 The option `drop='if_binary'` was added in 0.23... versionchanged:: 1.1 Support for dropping infrequent categories.",None
,"sparse_output sparse_output: bool, default=TrueWhen ``True``, it returns a :class:`scipy.sparse.csr_matrix`,i.e. a sparse matrix in ""Compressed Sparse Row"" (CSR) format... versionadded:: 1.2 `sparse` was renamed to `sparse_output`",False
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"handle_unknown handle_unknown: {'error', 'ignore', 'infrequent_if_exist', 'warn'}, default='error'Specifies the way unknown categories are handled during :meth:`transform`.- 'error' : Raise an error if an unknown category is present during transform.- 'ignore' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros. In the inverse transform, an unknown category will be denoted as None.- 'infrequent_if_exist' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will map to the infrequent category if it exists. The infrequent category will be mapped to the last position in the encoding. During inverse transform, an unknown category will be mapped to the category denoted `'infrequent'` if it exists. If the `'infrequent'` category does not exist, then :meth:`transform` and :meth:`inverse_transform` will handle an unknown category as with `handle_unknown='ignore'`. Infrequent categories exist based on `min_frequency` and `max_categories`. Read more in the :ref:`User Guide `.- 'warn' : When an unknown category is encountered during transform a warning is issued, and the encoding then proceeds as described for `handle_unknown=""infrequent_if_exist""`... versionchanged:: 1.1 `'infrequent_if_exist'` was added to automatically handle unknown categories and infrequent categories... versionadded:: 1.6 The option `""warn""` was added in 1.6.",'error'
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.1 Read more in the :ref:`User Guide `.",None
,"max_categ

In [13]:
encoder.categories_

[array(['ai', 'and', 'i', 'is', 'love', 'my', 'name', 'sunny'],
       dtype=object)]

In [14]:
print("Vocabulary:", encoder.categories_[0])

Vocabulary: ['ai' 'and' 'i' 'is' 'love' 'my' 'name' 'sunny']


In [15]:
tokens

[['my', 'name', 'is', 'sunny', 'and', 'i', 'love', 'ai']]

In [16]:
for sentence in tokens:
    print(sentence)

['my', 'name', 'is', 'sunny', 'and', 'i', 'love', 'ai']


In [17]:
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print(encoded_sentence)


Sentence: ['my', 'name', 'is', 'sunny', 'and', 'i', 'love', 'ai']
[[0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]]


# BOW

###### https://scikit-learn.org/0.15/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [20]:
document=["divesh is a good mentor he teaches us very well he teaches the project"]

AIM: Covert: Data: Number

In [21]:
bow = CountVectorizer()

In [22]:
bow_matrix =bow .fit_transform(document)

In [23]:
bow_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (1, 11)>

In [24]:
print("BOW Matrix:\n", bow_matrix.toarray())

BOW Matrix:
 [[1 1 2 1 1 1 2 1 1 1 1]]


In [25]:
bow.get_feature_names_out()

array(['divesh', 'good', 'he', 'is', 'mentor', 'project', 'teaches',
       'the', 'us', 'very', 'well'], dtype=object)

In [26]:
print("Vocabulary:", bow.get_feature_names_out())


Vocabulary: ['divesh' 'good' 'he' 'is' 'mentor' 'project' 'teaches' 'the' 'us' 'very'
 'well']


In [27]:
bow.fit(documents)

,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'
,"decode_error decode_error: {'strict', 'ignore', 'replace'}, default='strict'Instruction on what to do if a byte sequence is given to analyze thatcontains characters not of the given `encoding`. By default, it is'strict', meaning that a UnicodeDecodeError will be raised. Othervalues are 'ignore' and 'replace'.",'strict'
,"strip_accents strip_accents: {'ascii', 'unicode'} or callable, default=NoneRemove accents and perform other character normalizationduring the preprocessing step.'ascii' is a fast method that only works on characters that havea direct ASCII mapping.'unicode' is a slightly slower method that works on any characters.None (default) means no character normalization is performed.Both 'ascii' and 'unicode' use NFKD normalization from:func:`unicodedata.normalize`.",None
,"lowercase lowercase: bool, default=TrueConvert all characters to lowercase before tokenizing.",True
,"preprocessor preprocessor: callable, default=NoneOverride the preprocessing (strip_accents and lowercase) stage whilepreserving the tokenizing and n-grams generation steps.Only applies if ``analyzer`` is not callable.",None
,"tokenizer tokenizer: callable, default=NoneOverride the string tokenization step while preserving thepreprocessing and n-grams generation steps.Only applies if ``analyzer == 'word'``.",None
,"stop_words stop_words: {'english'}, list, default=NoneIf 'english', a built-in stop word list for English is used.There are several known issues with 'english' and you shouldconsider an alternative (see :ref:`stop_words`).If a list, that list is assumed to contain stop words, all of whichwill be removed from the resulting tokens.Only applies if ``analyzer == 'word'``.If None, no stop words will be used. In this case, setting `max_df`to a higher value, such as in the range (0.7, 1.0), can automatically detectand filter stop words based on intra corpus document frequency of terms.",None
,"token_pattern token_pattern: str or None, default=r""(?u)\\b\\w\\w+\\b""Regular expression denoting what constitutes a ""token"", only usedif ``analyzer == 'word'``. The default regexp select tokens of 2or more alphanumeric characters (punctuation is completely ignoredand always treated as a token separator).If there is a capturing group in token_pattern then thecaptured group content, not the entire match, becomes the token.At most one capturing group is permitted.",'(?u)\\b\\w\\w+\\b'
,"ngram_range ngram_range: tuple (min_n, max_n), default=(1, 1)The lower and upper boundary of the range of n-values for differentword n-grams or char n-grams to be extracted. All values of n suchsuch that min_n <= n <= max_n will be used. For example an``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` meansunigrams and bigrams, and ``(2, 2)`` means only bigrams.Only applies if ``analyzer`` is not callable.","(1, ...)"
,"analyzer analyzer: {'word', 'char', 'char_wb'} or callable, default='word'Whether the feature should be made of word n-gram or charactern-grams.Option 'char_wb' creates character n-grams only from text insideword boundaries; n-grams at the edges of words are padded with space.If a callable is passed it is used to extract the sequence of featuresout of the raw, unprocessed input... versionchanged:: 0.21Since v0.21, if ``input`` is ``filename`` or ``file``, the data isfirst read from the file and then passed to the given callableanalyzer.",'word'


In [28]:
documents

['people watch movie and watch movie again',
 'people watch cricket and watch cricket',
 'people like movie and like movie a lot',
 'people like cricket']

In [29]:
bow.transform(documents).toarray()

array([[1, 1, 0, 0, 0, 2, 1, 2],
       [0, 1, 2, 0, 0, 0, 1, 2],
       [0, 1, 0, 2, 1, 2, 1, 0],
       [0, 0, 1, 1, 0, 0, 1, 0]])

In [30]:
document = ["lion is the king of jungle"]

In [31]:
bow.transform(document)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 0 stored elements and shape (1, 8)>

# TF-IDF Practical

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [33]:
documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [34]:
tf_idf = TfidfVectorizer()

In [35]:
tf_idf_vector = tf_idf.fit_transform(documents)

In [36]:
tf_idf_vector

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 17 stored elements and shape (4, 8)>

In [37]:
tf_idf_vector.toarray()

array([[0.38771136, 0.24747114, 0.        , 0.        , 0.        ,
        0.61135218, 0.20232387, 0.61135218],
       [0.        , 0.2684707 , 0.66322944, 0.        , 0.        ,
        0.        , 0.21949239, 0.66322944],
       [0.        , 0.24747114, 0.        , 0.61135218, 0.38771136,
        0.61135218, 0.20232387, 0.        ],
       [0.        , 0.        , 0.64043405, 0.64043405, 0.        ,
        0.        , 0.42389674, 0.        ]])

In [38]:
for vector in tf_idf_vector.toarray():
    print(vector)

[0.38771136 0.24747114 0.         0.         0.         0.61135218
 0.20232387 0.61135218]
[0.         0.2684707  0.66322944 0.         0.         0.
 0.21949239 0.66322944]
[0.         0.24747114 0.         0.61135218 0.38771136 0.61135218
 0.20232387 0.        ]
[0.         0.         0.64043405 0.64043405 0.         0.
 0.42389674 0.        ]


In [39]:
tf_idf.get_feature_names_out()

array(['again', 'and', 'cricket', 'like', 'lot', 'movie', 'people',
       'watch'], dtype=object)

In [40]:
print("Vocabulary:", tf_idf.get_feature_names_out())

Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']
